runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: ber-serkr:us-east1:ber-serkr-dev

runtime_config:
    python_version: 3
    
health_check:
  enable_health_check: False